#!/bin/sh

# bspwmrc

## start sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &

## rules
bspc rule -r "*" # remove old bspwm rules
bspc rule -a Emacs state=tiled
bspc rule -a Zathura state=tiled

bspc config focus_follows_pointer true

## wm config
bspc monitor -d dev www sys mus chat misc

bspc config border_width 2
bspc config window_gap 20

bspc config split_ratio 0.5
bspc config borderless_monocle false
bspc config gapless_monocle false

## colors
. "${XDG_CONFIG_HOME:-$HOME/.config}/colors"
bspc config normal_border_color "$color7"
bspc config focused_border_color "$foreground"
bspc config presel_feedback_color "$color7"

## launch yabar
pgrep -x yabar > /dev/null || yabar &
