#! /bin/sh

# bspwmrc

## start sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &

## setup bspwm monitors
bspc monitor -d I II III IV V VI VII VIII IX X

## create window borders and gaps
bspc config border_width         2
bspc config window_gap           8

bspc config split_ratio          0.5
bspc config borderless_monocle   false
bspc config gapless_monocle      false

## configure colors
. "${HOME}/.cache/wal/colors.sh"

bspc config normal_border_color "$color1"
bspc config focused_border_color "$color12"

## launch polybar
#pgrep -x polybar > /dev/null || polybar default &
